modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Global%20Narration%20Toggle"
logoFile="icon.png"

[[mods]]
modId="globalnarrationtoggle"
version="1.2"
displayName="Global Narration Toggle"
displayURL="https://serilum.com/mod/global-narration-toggle"
authors="Rick South"
description='''Makes the narrator setting global, across instances. To turn it on and off. Creates a better start-up experience for all.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.globalnarrationtoggle]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.globalnarrationtoggle]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "globalnarrationtoggle.mixins.json"